### ISSUE TITLE
Is it possible to have a license associated with this project?

### ISSUE THREAD

**Issue by Zizouz212** [moomoohk/mootilities#1]
I'm interested in using some of the components, especially looking at a few of the pages listed here: http://moomoohk.github.io/snippets/java_osx.html

Would it be possible to assign the project a license, ideally a permissive one such as Apache?

**Comment by moomoohk** [comment]
Certainly! I'll get on it as soon as I can

**Comment by moomoohk** [comment]
[Here](https://github.com/moomoohk/mootilities/blob/master/LICENSE.txt) you go. Enjoy!

**Comment by Zizouz212** [comment]
Awesome! Thank you!
